# Generated by Django 4.0.5 on 2022-06-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='company',
        ),
    ]
