# Generated by Django 4.0.5 on 2022-06-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_order_category_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
    ]
