# Generated by Django 4.0.5 on 2022-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_of_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
