# Generated by Django 4.0.5 on 2022-06-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_order_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_position',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('orphan_paid', 'Orphan Paid'), ('full_paid', 'Full Paid')], default='not_paid', max_length=30),
        ),
    ]
