# Generated by Django 4.0.5 on 2022-06-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_paid_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_money',
            new_name='paid_price',
        ),
    ]
